[platformio]
default_envs = pro16MHzatmega328

[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main_test.cpp>

[env:pro16MHzatmega328-test]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_test.cpp>

[env:screen]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.7.0
build_src_filter = -<*> +<../screen/main.cpp>
build_flags = -DSERIAL_TX_BUFFER_SIZE=16 -DSERIAL_RX_BUFFER_SIZE=16

[env:screen-diag]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
lib_deps = fastled/FastLED@^3.7.0
build_src_filter = -<*> +<../screen/main_diag.cpp>
build_flags = -DSERIAL_TX_BUFFER_SIZE=16 -DSERIAL_RX_BUFFER_SIZE=16
