[platformio]
default_envs = pro16MHzatmega328

[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<main_test.cpp>

[env:pro16MHzatmega328-test]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_test.cpp>

[env:ht16k33-test]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_ht16k33_test.cpp>
