// Snake attack — generated by f1_lights studio.
// Edited by hand? Re-generating from the studio will overwrite this file.
// Included inside an anonymous namespace by esp32-screen/main.cpp.

// ===================== SNAKE ATTACK =====================
// Green snake, glowing red apple. Every 5 apples: faster!
// Arrow controls: LEFT / RIGHT, ROTATE = UP, DROP = DOWN.
// Edges wrap around, so you only lose by biting yourself.

static const uint16_t kRing = 512;           // 16*32 cells max
static uint8_t  s_bx[kRing];
static uint8_t  s_by[kRing];
static uint16_t s_head = 0;
static uint16_t s_len = 0;
static uint8_t  s_grid[32][16];              // 1 = snake body

static uint8_t  s_dir = 0;                   // 0 up, 1 right, 2 down, 3 left
static uint8_t  s_q[2];
static uint8_t  s_qn = 0;
static uint8_t  s_grow = 0;

static uint8_t  s_ax = 0, s_ay = 0;          // apple
static uint16_t s_apples = 0;
static uint8_t  s_level = 0;
static bool     s_won = false;

static uint8_t  s_sparkX = 0, s_sparkY = 0;
static uint32_t s_sparkT = 0;
static bool     s_sparkOn = false;
static uint32_t s_levelFlashUntil = 0;

enum GameState : uint8_t { ST_READY, ST_PLAY, ST_DYING, ST_OVER };
static GameState s_state = ST_READY;
static uint32_t s_stateT = 0;
static uint32_t s_nextStep = 0;
static uint32_t s_nextFrame = 0;

static bool s_pU = false, s_pD = false, s_pL = false, s_pR = false, s_pB = false;

static const int8_t kDX[4] = { 0, 1, 0, -1 };
static const int8_t kDY[4] = { -1, 0, 1, 0 };

static const uint16_t kFont[10] = {
  0x7B6F, 0x2C97, 0x73E7, 0x73CF, 0x5BC9,
  0x79CF, 0x79EF, 0x7292, 0x7BEF, 0x7BCF
};

static uint16_t stepInterval() {
  int32_t ms = 230 - (int32_t)s_level * 25;
  if (ms < 70) ms = 70;
  return (uint16_t)ms;
}

static bool placeApple() {
  uint16_t freeCount = 0;
  for (uint8_t y = 0; y < 32; y++)
    for (uint8_t x = 0; x < 16; x++)
      if (!s_grid[y][x]) freeCount++;
  if (freeCount == 0) return false;
  uint16_t k = (uint16_t)random(freeCount);
  for (uint8_t y = 0; y < 32; y++)
    for (uint8_t x = 0; x < 16; x++)
      if (!s_grid[y][x]) {
        if (k == 0) { s_ax = x; s_ay = y; return true; }
        k--;
      }
  return false;
}

static void resetGame() {
  memset(s_grid, 0, sizeof(s_grid));
  s_head = 0;
  s_len = 0;
  for (uint8_t i = 0; i < 3; i++) {          // tail first, head last
    uint8_t x = 7, y = 26 - i;
    s_head = i;
    s_bx[i] = x; s_by[i] = y;
    s_grid[y][x] = 1;
    s_len++;
  }
  s_dir = 0;
  s_qn = 0;
  s_grow = 0;
  s_apples = 0;
  s_level = 0;
  s_won = false;
  s_sparkOn = false;
  s_levelFlashUntil = 0;
  // Put the first apple somewhere reachable-looking, above the snake
  s_ax = (uint8_t)random(2, 14);
  s_ay = (uint8_t)random(4, 14);
  s_state = ST_READY;
  s_stateT = millis();
}

static void pushDir(uint8_t d) {
  uint8_t last = s_qn ? s_q[s_qn - 1] : s_dir;
  if (d == last || d == ((last + 2) & 3)) return;
  if (s_qn < 2) s_q[s_qn++] = d;
}

static void die(uint32_t now) {
  s_state = ST_DYING;
  s_stateT = now;
}

static void stepSnake(uint32_t now) {
  if (s_qn) {
    s_dir = s_q[0];
    s_q[0] = s_q[1];
    s_qn--;
  }
  uint8_t hx = s_bx[s_head], hy = s_by[s_head];
  uint8_t nx = (uint8_t)((hx + kDX[s_dir] + 16) & 15);
  uint8_t ny = (uint8_t)((hy + kDY[s_dir] + 32) & 31);

  if (s_grow == 0) {
    uint16_t t = (uint16_t)((s_head - (s_len - 1)) & (kRing - 1));
    s_grid[s_by[t]][s_bx[t]] = 0;
    s_len--;
  } else {
    s_grow--;
  }

  if (s_grid[ny][nx]) { die(now); return; }

  s_head = (uint16_t)((s_head + 1) & (kRing - 1));
  s_bx[s_head] = nx; s_by[s_head] = ny;
  s_grid[ny][nx] = 1;
  s_len++;

  if (nx == s_ax && ny == s_ay) {
    s_apples++;
    s_grow += 2;
    s_sparkX = nx; s_sparkY = ny; s_sparkT = now; s_sparkOn = true;
    if (s_apples % 5 == 0) {
      s_level++;
      s_levelFlashUntil = now + 500;
    }
    if (!placeApple()) {
      s_won = true;
      s_state = ST_OVER;
      s_stateT = now;
    }
  }
}

static void drawDigit(int x0, int y0, uint8_t d, uint8_t col) {
  uint16_t bits = kFont[d];
  for (uint8_t r = 0; r < 5; r++)
    for (uint8_t c = 0; c < 3; c++)
      if (bits & (1u << (14 - (r * 3 + c))))
        screen_panel::setPixel(x0 + c, y0 + r, col);
}

static void drawNumber(uint16_t n, int y0, uint8_t col) {
  if (n > 999) n = 999;
  uint8_t digits[3];
  uint8_t cnt = 0;
  do { digits[cnt++] = n % 10; n /= 10; } while (n && cnt < 3);
  int w = cnt * 4 - 1;
  int x = (16 - w) / 2;
  for (int i = cnt - 1; i >= 0; i--) {
    drawDigit(x, y0, digits[i], col);
    x += 4;
  }
}

static uint8_t rainbow(uint8_t i) {
  static const uint8_t cols[6] = {
    pack(3,0,0), pack(3,2,0), pack(3,3,0), pack(0,3,0), pack(0,2,3), pack(2,0,3)
  };
  return cols[i % 6];
}

static void drawApple(uint32_t now) {
  bool bright = ((now / 250) & 1) != 0;
  if (bright) {
    uint8_t halo = pack(1,0,0);
    screen_panel::setPixel((s_ax + 1) & 15, s_ay, halo);
    screen_panel::setPixel((s_ax + 15) & 15, s_ay, halo);
    screen_panel::setPixel(s_ax, (s_ay + 1) & 31, halo);
    screen_panel::setPixel(s_ax, (s_ay + 31) & 31, halo);
  }
  screen_panel::setPixel(s_ax, s_ay, bright ? pack(3,1,1) : pack(3,0,0));
}

static void drawSnake(uint32_t now, bool dying) {
  bool flashRed = dying && ((now / 120) & 1);
  for (uint16_t i = 0; i < s_len; i++) {
    uint16_t idx = (uint16_t)((s_head - i) & (kRing - 1));
    uint8_t col;
    if (dying) {
      col = flashRed ? pack(3,0,0) : pack(3,3,3);
    } else if (i == 0) {
      col = pack(2,3,1);                         // bright head
    } else if (i == s_len - 1) {
      col = pack(0,1,0);                         // dim tail tip
    } else {
      col = ((i >> 1) & 1) ? pack(0,2,0) : pack(0,3,0);   // stripes
    }
    screen_panel::setPixel(s_bx[idx], s_by[idx], col);
  }
}

static void drawSparkle(uint32_t now) {
  if (!s_sparkOn) return;
  uint32_t age = now - s_sparkT;
  if (age > 350) { s_sparkOn = false; return; }
  int d = 1 + (int)(age / 90);
  uint8_t col = (age < 175) ? pack(3,3,3) : pack(3,3,0);
  int x = s_sparkX, y = s_sparkY;
  screen_panel::setPixel(x - d, y - d, col);
  screen_panel::setPixel(x + d, y - d, col);
  screen_panel::setPixel(x - d, y + d, col);
  screen_panel::setPixel(x + d, y + d, col);
}

static void drawLevelFlash(uint32_t now) {
  if ((int32_t)(s_levelFlashUntil - now) <= 0) return;
  uint8_t shift = (uint8_t)(now / 60);
  for (uint8_t x = 0; x < 16; x++) {
    screen_panel::setPixel(x, 0, rainbow(x + shift));
    screen_panel::setPixel(x, 31, rainbow(x + shift + 3));
  }
  for (uint8_t y = 0; y < 32; y++) {
    screen_panel::setPixel(0, y, rainbow(y + shift));
    screen_panel::setPixel(15, y, rainbow(y + shift + 3));
  }
}

static void drawOver(uint32_t now) {
  // Apple icon
  bool bright = ((now / 300) & 1) != 0;
  uint8_t red = bright ? pack(3,0,0) : pack(2,0,0);
  screen_panel::setPixel(8, 2, pack(0,3,0));   // leaf
  screen_panel::setPixel(7, 3, pack(1,1,0));   // stem
  for (uint8_t y = 4; y < 8; y++)
    for (uint8_t x = 6; x < 9; x++)
      screen_panel::setPixel(x, y, red);
  screen_panel::setPixel(5, 5, red);
  screen_panel::setPixel(9, 5, red);
  screen_panel::setPixel(5, 6, red);
  screen_panel::setPixel(9, 6, red);
  screen_panel::setPixel(6, 4, pack(3,2,2));   // shine

  // Score
  uint8_t scoreCol = s_won ? rainbow((uint8_t)(now / 80)) : pack(3,3,0);
  drawNumber(s_apples, 11, scoreCol);

  // Level dots (one green dot per speed-up)
  uint8_t lv = s_level > 14 ? 14 : s_level;
  int x0 = (16 - (int)lv) / 2;
  for (uint8_t i = 0; i < lv; i++)
    screen_panel::setPixel(x0 + i, 19, pack(0,3,0));

  // Little green snake wiggling at the bottom = "press to play"
  if (now - s_stateT > 700) {
    uint8_t off = (uint8_t)((now / 100) % 16);
    for (uint8_t i = 0; i < 5; i++) {
      uint8_t x = (uint8_t)((off + 16 - i) & 15);
      uint8_t y = 26 + ((x >> 1) & 1);
      screen_panel::setPixel(x, y, i == 0 ? pack(2,3,1) : pack(0,2,0));
    }
  }
}

void gameSetup() {
  randomSeed(micros());
  resetGame();
  uint32_t now = millis();
  s_nextFrame = now;
  s_nextStep = now;
}

void gameTick() {
  uint32_t now = millis();

  bool u = peripherals::buttonRotate();
  bool d = peripherals::buttonDrop();
  bool l = peripherals::buttonLeft();
  bool r = peripherals::buttonRight();
  bool b = peripherals::buttonBomb();
  bool eu = u && !s_pU, ed = d && !s_pD, el = l && !s_pL, er = r && !s_pR, eb = b && !s_pB;
  s_pU = u; s_pD = d; s_pL = l; s_pR = r; s_pB = b;
  bool anyEdge = eu || ed || el || er || eb;

  switch (s_state) {
    case ST_READY:
      if (eu) pushDir(0);
      if (er) pushDir(1);
      if (el) pushDir(3);
      // DOWN at start would bite our own neck, so it just starts going up
      if (anyEdge || now - s_stateT > 3000) {
        s_state = ST_PLAY;
        s_nextStep = now;
      }
      break;

    case ST_PLAY:
      if (eu) pushDir(0);
      if (er) pushDir(1);
      if (ed) pushDir(2);
      if (el) pushDir(3);
      if ((int32_t)(now - s_nextStep) >= 0) {
        s_nextStep = now + stepInterval();
        stepSnake(now);
      }
      break;

    case ST_DYING:
      if (now - s_stateT > 1500) {
        s_state = ST_OVER;
        s_stateT = now;
      }
      break;

    case ST_OVER:
      if (anyEdge && now - s_stateT > 700) {
        resetGame();
      }
      break;
  }

  if ((int32_t)(now - s_nextFrame) < 0) return;
  s_nextFrame = now + 25;   // ~40 fps

  screen_panel::clearAll();
  if (s_state == ST_OVER) {
    drawOver(now);
  } else {
    drawApple(now);
    if (s_state == ST_READY && ((now / 200) & 1)) {
      // blink the head so the child sees where the snake is
      uint16_t saved = s_len;
      drawSnake(now, false);
      screen_panel::setPixel(s_bx[s_head], s_by[s_head], pack(3,3,3));
      (void)saved;
    } else {
      drawSnake(now, s_state == ST_DYING);
    }
    drawSparkle(now);
    drawLevelFlash(now);
  }
  screen_panel::show();
}
